version: "3.5"

services:
  sim:
    build: ./net-sim
    container_name: sim
    hostname: sim
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sim:/logs
    environment:
      - SCENARIO=$SCENARIO
    cap_add: 
      - NET_ADMIN
    expose:
      - "57832"
    networks:
      leftnet:
        ipv4_address: 193.167.0.2
        ipv6_address: fd00:cafe:cafe:0::2
      rightnet:
        ipv4_address: 193.167.100.2
        ipv6_address: fd00:cafe:cafe:100::2


networks:
  leftnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.167.0.0/24
        - subnet: fd00:cafe:cafe:0::/64
  rightnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.167.100.0/24
        - subnet: fd00:cafe:cafe:100::/64
