listen_addr = "0.0.0.0:8808"
network = "raknet"

[[llm]]
name = "tinyllama-0.5m"              # The name of the model, it is used to identify the model
model = "./TinyLLama-v0-5M-F16.gguf"
probability = 0.9                    # The probability of the model to generate the next token, it is used to control the randomness of the model
temperature = 1.0                    # The temperature of the model, it is used to control the randomness of the model
threads = 8                          # Number of threads to run the model
mlock = false                        # Enable mlock to lock the memory, it reduces the risk of swapping to disk

[[llm]]
name = "gemma-2b-it"                # The name of the model, it is used to identify the model
model = "./gemma-2b-it-q8_0.gguf"
probability = 0.9                    # The probability of the model to generate the next token, it is used to control the randomness of the model
temperature = 1.0                    # The temperature of the model, it is used to control the randomness of the model
threads = 8                          # Number of threads to run the model
mlock = false                        # Enable mlock to lock the memory, it reduces the risk of swapping to disk

[[llm]]
name = "deepseek-r1-1.5b"            # The name of the model, it is used to identify the model
model = "./DeepSeek-R1-Distill-Qwen-1.5B-Q8_0.gguf"
probability = 0.9                    # The probability of the model to generate the next token, it is used to control the randomness of the model
temperature = 1.0                    # The temperature of the model, it is used to control the randomness of the model
threads = 8                          # Number of threads to run the model
mlock = false                        # Enable mlock to lock the memory, it reduces the risk of swapping to disk

[whisper]
model = "./whisper-tiny-ggml-tiny.bin"  # The path to the whisper model
language = "en"                         # The language of the whisper model

[kokoro]
model = "./kokoro-v1.0.onnx"         # The path to the kokoro model
voice = "./voices-v1.0.bin"          # The path to the voice data
style = "af_sarah.4+af_nicole.6"     # The style of the voice, it is used to control the tone and pitch of the voice
speed = 1.0                          # The speed of the voice, it is used to control the speed of the voice

[raknet]
sever_guid = 4170652262067404866
advertisement = "Hi, I am server"
min_mtu = 480
max_mtu = 1480
support_version = [9, 11, 13]
max_pending = 1024
max_parted_size = 256
max_parted_count = 256
max_channels = 255                # DO NOT MODIFY IT

[tcp]
ttl = 60
nodelay = false
