[package]
name = "crabwaifu-server"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crabml = { workspace = true }
crabml-llama2 = { workspace = true }
crabwaifu-common = { workspace = true }
env_logger = "0.11"
log = "0.4"
tokio = { version = "1", features = ["full"] }
raknet-rs = { workspace = true }
futures = { version = "0.3.5", default-features = false }
