[package]
name = "crabwaifu-server"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
crabml = { workspace = true }
crabml-llama2 = { workspace = true }
raknet-rs = { workspace = true }
num_cpus = "1.16.0"
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"
clap = { version = "4.0", features = ["derive"] }
