[package]
name = "crabwaifu-client"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
raknet-rs = { workspace = true }
crabwaifu-common = { workspace = true }
tokio = { version = "1", features = ["full"] }
env_logger = "0.11"
clap = { version = "4.0", features = ["derive"] }